export const baseUrl = "https://www.welcometothejungle.com/fr/jobs"
export const countryQuery = "refinementList[offices.country_code][]"
export const contractTypeQuery = "refinementList[contract_type][]"
export const aroundQuery = "aroundQuery"
export const paramsQuery = "query"
export const pageQuery = "page"
