name: MasterPush

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # Check that tests pass and tat the project is buildable.
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Run starting deployment
        run: echo Starting Deployment…
      
      - name: Check the current Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: "21.x"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run test
        run: npm run test

      - name: Run Build
        run: npm run build

  # Simple deployment.
  deploy:
    runs-on: ubuntu-latest
    needs: [test-build]
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          


